import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Script from "next/script";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/">About Us</Link>
        <p>Hello World</p>
      </main>
      <Script
        src="https://static-staging.enalog.app/autotrack-debug.min.js"
        data-name="enalog"
        data-enalog-token="AC14Z35S87A66XNTKZTAEFWO"
        data-enalog-project="test"
        onReady={() => {
          initAutotrackDebug();
        }}
      />
    </>
  );
}
